### ISSUE TITLE
Add amazon link to kml.deltares.nl

### ISSUE THREAD

**Issue by SiggyF** [openearth/coastviewer#13]
Find the kustviewer.kml and update the link to point to 

http://dev-env.myfjvt76zf.eu-west-1.elasticbeanstalk.com/coastviewer/1.1.0/transects/kml

**Comment by SiggyF** [comment]
New server is at 
http://coastal-dev.zdcxwh5vkz.eu-west-1.elasticbeanstalk.com/coastviewer/1.1.0/transects/kml

**Comment by giosans** [comment]
updated in the kustviewer.kml
